Algoritmo "LISTA 3 - EXERCÍCIO 8"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2024
Var
cont,numero:inteiro

Inicio
numero<-5
repita
cont<-cont+1
numero<- cont+numero
escreva(numero)
ate numero>=50

Fimalgoritmo