Algoritmo "LIsta 3 - Exercício 6"

Var
nome, sexo: caracter
idade: inteiro


Inicio
escreva("Insira seu nome: ")
leia(nome)
escreva("Insira idade:")
leia (idade)
escreva ("Qual seu sexo? (M/F)")
leia (sexo)


se idade >=10 entao
escreval("Usuário:",nome)
escreval("Idade:",idade)
escreval("Sexo:",sexo)

senao
escreva("Usuário deve ter entre 10 a 100 anos")
fimse


Fimalgoritmo